### ISSUE TITLE
User canceled the Dialog flow

### ISSUE THREAD

**Issue by Giggiux** [julianlam/nodebb-plugin-sso-facebook#38]
Hi, I'm getting this error and I don't really know why (doesn't affect the usability of the website for now), but it's repeated more and more time in the logs:

```js
Oct 19 20:20:40 nodebb[24281]:  FacebookAuthorizationError: User canceled the Dialog flow
Oct 19 20:20:40 nodebb[24281]:     at Strategy.authenticate (/var/nodebb/node_modules/passport-facebook/lib/strategy.js:81:23)
Oct 19 20:20:40 nodebb[24281]:     at attempt (/var/nodebb/node_modules/passport/lib/middleware/authenticate.js:348:16)
Oct 19 20:20:40 nodebb[24281]:     at authenticate (/var/nodebb/node_modules/passport/lib/middleware/authenticate.js:349:7)
Oct 19 20:20:40 nodebb[24281]:     at Layer.handle [as handle_request] (/var/nodebb/node_modules/express/lib/router/layer.js:95:5)
Oct 19 20:20:40 nodebb[24281]:     at next (/var/nodebb/node_modules/express/lib/router/route.js:131:13)
Oct 19 20:20:40 nodebb[24281]:     at Route.dispatch (/var/nodebb/node_modules/express/lib/router/route.js:112:3)
Oct 19 20:20:40 nodebb[24281]:     at Layer.handle [as handle_request] (/var/nodebb/node_modules/express/lib/router/layer.js:95:5)
Oct 19 20:20:40 nodebb[24281]:     at /var/nodebb/node_modules/express/lib/router/index.js:277:22
Oct 19 20:20:40 nodebb[24281]:     at Function.process_params (/var/nodebb/node_modules/express/lib/router/index.js:330:12)
Oct 19 20:20:40 nodebb[24281]:     at next (/var/nodebb/node_modules/express/lib/router/index.js:271:10)
Oct 19 20:20:40 nodebb[24281]:     at Function.handle (/var/nodebb/node_modules/express/lib/router/index.js:176:3)
Oct 19 20:20:40 nodebb[24281]:     at router (/var/nodebb/node_modules/express/lib/router/index.js:46:12)
Oct 19 20:20:40 nodebb[24281]:     at Layer.handle [as handle_request] (/var/nodebb/node_modules/express/lib/router/layer.js:95:5)
Oct 19 20:20:40 nodebb[24281]:     at trim_prefix (/var/nodebb/node_modules/express/lib/router/index.js:312:13)
Oct 19 20:20:40 nodebb[24281]:     at /var/nodebb/node_modules/express/lib/router/index.js:280:7
Oct 19 20:20:40 nodebb[24281]:     at Function.process_params (/var/nodebb/node_modules/express/lib/router/index.js:330:12)
```

**Comment by julianlam** [comment]
Hi there, seems like this error happens when they try to log in via facebook but hit the cancel button. You can ignore it :)
