### ISSUE TITLE
TypeError: Cannot read property 'endsWith' of null

### ISSUE THREAD

**Issue by Dabada** [julianlam/nodebb-plugin-sso-facebook#39]
```
18/12 23:13 [58] - error: TypeError: Cannot read property 'endsWith' of null
    at /usr/src/app/node_modules/nodebb-plugin-sso-facebook/library.js:144:14
    at /usr/src/app/src/user/data.js:18:4
    at /usr/src/app/src/user/data.js:24:4
    at /usr/src/app/src/plugins/hooks.js:120:4
    at /usr/src/app/node_modules/async/lib/async.js:380:13
    at /usr/src/app/node_modules/async/lib/async.js:52:16
    at /usr/src/app/node_modules/async/lib/async.js:269:32
    at /usr/src/app/node_modules/async/lib/async.js:44:16
    at /usr/src/app/node_modules/async/lib/async.js:377:17
    at Object.plugin.onForceEnabled [as method] (/usr/src/app/node_modules/nodebb-plugin-gravatar/library.js:120:3)
    at /usr/src/app/src/plugins/hooks.js:114:12
    at /usr/src/app/node_modules/async/lib/async.js:375:13
    at iterate (/usr/src/app/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/usr/src/app/node_modules/async/lib/async.js:281:9)
    at Object.async.inject.async.foldl.async.reduce (/usr/src/app/node_modules/async/lib/async.js:374:15)
    at fireFilterHook (/usr/src/app/src/plugins/hooks.js:106:9)
    at Object.Plugins.fireHook (/usr/src/app/src/plugins/hooks.js:87:5)
    at modifyUserData (/usr/src/app/src/user/data.js:150:11)
    at /usr/src/app/src/user/data.js:63:4
    at Multi.callback (/usr/src/app/src/database/redis/hash.js:74:4)
    at multi_callback (/usr/src/app/node_modules/redis/lib/multi.js:89:14)
    at Command.callback (/usr/src/app/node_modules/redis/lib/multi.js:116:9)
TypeError: Cannot read property 'endsWith' of null
    at /usr/src/app/node_modules/nodebb-plugin-sso-facebook/library.js:144:14
    at /usr/src/app/src/user/data.js:18:4
    at /usr/src/app/src/user/data.js:24:4
    at /usr/src/app/src/plugins/hooks.js:120:4
    at /usr/src/app/node_modules/async/lib/async.js:380:13
    at /usr/src/app/node_modules/async/lib/async.js:52:16
    at /usr/src/app/node_modules/async/lib/async.js:269:32
    at /usr/src/app/node_modules/async/lib/async.js:44:16
    at /usr/src/app/node_modules/async/lib/async.js:377:17
    at Object.plugin.onForceEnabled [as method] (/usr/src/app/node_modules/nodebb-plugin-gravatar/library.js:120:3)
    at /usr/src/app/src/plugins/hooks.js:114:12
    at /usr/src/app/node_modules/async/lib/async.js:375:13
    at iterate (/usr/src/app/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/usr/src/app/node_modules/async/lib/async.js:281:9)
    at Object.async.inject.async.foldl.async.reduce (/usr/src/app/node_modules/async/lib/async.js:374:15)
    at fireFilterHook (/usr/src/app/src/plugins/hooks.js:106:9)
    at Object.Plugins.fireHook (/usr/src/app/src/plugins/hooks.js:87:5)
    at modifyUserData (/usr/src/app/src/user/data.js:150:11)
    at /usr/src/app/src/user/data.js:63:4
    at Multi.callback (/usr/src/app/src/database/redis/hash.js:74:4)
    at multi_callback (/usr/src/app/node_modules/redis/lib/multi.js:89:14)
    at Command.callback (/usr/src/app/node_modules/redis/lib/multi.js:116:9)
```

**Comment by julianlam** [comment]
v3.0.4

**Comment by Dabada** [comment]
I've found a fix around (not to do in production)
* find the user id (uid) (check users on NodeBB admin page)
* delete the user
* connect to redis
   * find the association between facebook id and nodebb id  ```HGETALL "fbid:uid"```
   * delete the association ```hdel "fbid:uid" {user_fbid}```
   * reconnect with FB SSO

**Comment by Dabada** [comment]
@julianlam thank's for your Fix and for your FB SSO plugin.
